import { existsSync, readFileSync, mkdirSync, writeFileSync, unlinkSync, lstatSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { shared } from './shared.js';
import { atomicJSON, readJSON, safePath } from '../workflow.js';
import { managedPath } from './layout.js';

const ARTIFACTS = new Set(['auteric/connection.json','auteric/runtime-connection.json','auteric/deployment.json','auteric/deploy.json','auteric/task-definition.json','auteric/compose.yaml']);
const allowedArtifact = relative => ARTIFACTS.has(relative) || relative === 'auteric/.gitignore'
  || /^auteric\/(?:adapter|private-hook)\.mjs$/.test(relative)
  || /^auteric\/tests\/[a-zA-Z0-9_-]+\.mjs$/.test(relative);
const fingerprint = content => 'sha256:' + createHash('sha256').update(content).digest('hex');
export function initializeManaged(root) {
  const directory = safePath(join(root,'auteric'));
  const ignore = safePath(join(directory,'.gitignore'));
  const createdIgnore = !existsSync(ignore);
  // The folder owns every generated repository file. Private mutable state
  // and service-issued discovery must never enter a merchant commit.
  if(existsSync(ignore)) {
    const rules = readFileSync(ignore,'utf8').split(/\r?\n/);
    if(!rules.includes('/.state/') || !rules.includes('/discovery/'))
      throw Error('artifact_conflict: auteric/.gitignore must ignore /.state/ and /discovery/');
  } else {
    mkdirSync(directory,{recursive:true,mode:0o700});

  }
  const state=safePath(join(directory,'.state'));
  mkdirSync(state,{recursive:true,mode:0o700});
  if(lstatSync(state).mode&0o077 || lstatSync(state).uid!==process.getuid())
    throw Error('artifact_conflict: auteric/.state must be private and owned by the CLI user');
  if(createdIgnore) {
    const content='/.state/\n/discovery/\n', path=managedPath(root,'artifacts.json');
    atomicJSON(path,{...(readJSON(path)||{}),'auteric/.gitignore':fingerprint(content)});
    writeFileSync(ignore,content,{flag:'wx',mode:0o644});
  }
}

export async function ownedArtifact(root, relative) {
  if(!allowedArtifact(relative))throw Error('unknown merchant artifact');
  const {safeTarget}=await shared('atomic');
  const path=safeTarget(join(root,relative));
  const ledger=readJSON(managedPath(root,'artifacts.json')) || {};
  return existsSync(path) && ledger[relative]===fingerprint(readFileSync(path));
}

export async function removeArtifacts(root, installationId) {
  const {safeTarget}=await shared('atomic');
  const ledger=readJSON(managedPath(root,'artifacts.json')) || {}, removed=[], retained=[];
  for(const relative of Object.keys(ledger)) {
    if(!allowedArtifact(relative))throw Error('invalid artifact ownership ledger');
    const path=safeTarget(join(root,relative));
    if(!existsSync(path))continue;
    if(await ownedArtifact(root,relative)){unlinkSync(path);removed.push(relative);}
    else retained.push(relative);
  }
  const discovery=safeTarget(join(root,'auteric/discovery/ucp'));
  const receipt=safeTarget(join(root,'auteric/discovery/.auteric-owner.json'));
  if(existsSync(discovery)) {
    const owner=readJSON(receipt);
    if(owner?.installation_id===installationId && owner.digest===fingerprint(readFileSync(discovery))) {
      unlinkSync(discovery);unlinkSync(receipt);removed.push('auteric/discovery/ucp');
    } else retained.push('auteric/discovery/ucp');
  }
  const secret=safeTarget(managedPath(root,'enrollment.json'));
  if(existsSync(secret)) {
    if(readJSON(secret)?.installation_id===installationId){unlinkSync(secret);removed.push('auteric/.state/enrollment.json');}
    else retained.push('auteric/.state/enrollment.json');
  }
  return {removed,retained};
}

/** Preflight every target before replacing any file. Existing merchant bytes are never overwritten. */
export async function writeArtifacts(root, artifacts, { dryRun=false }={}) {
  const {safeTarget,atomicWrite}=await shared('atomic');
  const changes=[];
  for(const [relative,content] of Object.entries(artifacts)) {
    if(!allowedArtifact(relative))throw Error('unknown merchant artifact');
    const path=safeTarget(join(root,relative));
    if(existsSync(path)) {
      if(readFileSync(path,'utf8')!==content)throw Error(`artifact_conflict: ${relative} changed; review mapping drift or merchant edits before replacing`);
    }else changes.push({path,content});
  }
  if(!dryRun) {
    initializeManaged(root);
    // Persist ownership before writing so an interrupted install can still
    // safely remove matching generated bytes; edited bytes are preserved.
    const path=managedPath(root,'artifacts.json'),ledger=readJSON(path)||{};
    for(const [relative,content] of Object.entries(artifacts)) {
      if(!existsSync(join(root,relative)) || ledger[relative]===fingerprint(content))ledger[relative]=fingerprint(content);
    }
    atomicJSON(path,ledger);
    for(const {path,content} of changes)atomicWrite(path,content,0o644);
  }
  return {files_written:dryRun?0:changes.length,changes:changes.map(c=>c.path),no_op:changes.length===0};
}
