let csrf="",cart=null,pending=null,lastUnknownRequestId=null;
const $=id=>document.getElementById(id);
const requestId=()=>crypto.randomUUID().replaceAll("-","");
const status=(message,kind="")=>{$("status").textContent=message;$("status").dataset.kind=kind};
const run=fn=>(...args)=>Promise.resolve(fn(...args)).catch(error=>status(error.message,"error"));
async function api(path,options={}){const response=await fetch(path,{credentials:"same-origin",redirect:"error",...options,headers:{"content-type":"application/json",...(options.method&&options.method!=="GET"?{"x-auteric-csrf":csrf}:{}),...options.headers}});const body=await response.json();if(!response.ok)throw new Error(body.detail||`HTTP ${response.status}`);return body}
function applyOutcome(result,operation,input,request_id){if(result.status==="approval_required"){pending={...result,operation,input};renderApproval();status(result.reason,"error")}else if(result.status==="executed"){if(!pending||pending.request_id===request_id){pending=null;renderApproval()}if(Array.isArray(result.result)&&operation==="search_products")renderProducts(result.result);else if(result.result?.items&&["create_cart","get_cart","add_to_cart","update_cart_item","remove_from_cart"].includes(operation)){cart=result.result;renderCart()}status(`${operation} executed through Auteric${result.replayed?" (replayed receipt)":""}`,"ok")}else if(result.status==="unknown"){lastUnknownRequestId=request_id;$("reconcile").disabled=false;status(result.reason||"Write outcome is unknown. Do not retry.","error")}else status(result.reason||"Action was not confirmed",result.status==="blocked"?"error":"")}
async function execute(operation,input,request_id=requestId()){const result=await api("/api/auteric/execute",{method:"POST",headers:{"idempotency-key":request_id,"x-auteric-request":"gateway-v1"},body:JSON.stringify({operation,input,request_id})});applyOutcome(result,operation,input,request_id);return result}
function renderProducts(items){const root=$("products");root.textContent="";for(const product of items){const card=document.createElement("article");card.className="product";const title=document.createElement("h3");title.textContent=product.title;const description=document.createElement("p");description.textContent=product.description||`SKU ${product.sku}`;const price=document.createElement("div");price.className="price";price.textContent=new Intl.NumberFormat("en-US",{style:"currency",currency:product.currency}).format(product.price);let variants=null;if(product.variants?.length){variants=document.createElement("select");variants.className="variant-select";variants.setAttribute("aria-label",`Variant for ${product.title}`);for(const variant of product.variants){const option=document.createElement("option");option.value=variant.id;option.textContent=`${variant.sku} · $${variant.price}`;variants.append(option)}}const button=document.createElement("button");button.textContent="Add with Auteric";button.addEventListener("click",run(()=>add(product.id,variants?.value)));card.append(title,description,price,...(variants?[variants]:[]),button);root.append(card)}}
function renderCart(){const root=$("cart");root.textContent="";if(!cart){root.innerHTML='<p class="muted">No cart yet.</p>';$("checkout").disabled=true;$("arm-fault").disabled=true;return}for(const item of cart.items){const row=document.createElement("div");row.className="cart-row";const name=document.createElement("span");name.textContent=`${item.sku} × ${item.quantity}`;const value=document.createElement("strong");value.textContent=`$${item.total_price}`;row.append(name,value);root.append(row)}const total=document.createElement("div");total.className="cart-row";total.innerHTML=`<strong>Total</strong><strong>$${cart.total}</strong>`;root.append(total);$("checkout").disabled=!cart.items.length;$("arm-fault").disabled=false}
function renderApproval(){const root=$("approval");root.textContent="";root.hidden=!pending;if(!pending)return;const text=document.createElement("div");text.textContent=`${pending.reason} Approve ${pending.operation} (${pending.request_id}): ${JSON.stringify(pending.input)}`;const button=document.createElement("button");button.textContent="Approve this exact request";button.addEventListener("click",run(approve));root.append(text,button)}
async function loadProducts(){const response=await execute("search_products",{query:"",limit:20});if(response.status==="executed")renderProducts(response.result)}
async function createCart(){const response=await execute("create_cart",{currency:"USD",items:[]});if(response.status==="executed"){cart=response.result;renderCart();await loadTraffic()}}
async function add(product_id,variant_id){if(!cart)await createCart();if(!cart)return;const input={cart_id:cart.id,product_id,quantity:1};if(variant_id)input.variant_id=variant_id;const response=await execute("add_to_cart",input);if(response.status==="executed"){cart=response.result;renderCart();await loadTraffic()}}
async function checkout(){const response=await execute("create_checkout",{cart_id:cart.id});if(response.status==="executed"){status(`Checkout handoff ${response.result.id} created. No payment was executed.`,"ok");await loadTraffic()}}
async function approve(){if(!pending)return;const response=await api("/api/auteric/approve",{method:"POST",body:JSON.stringify({request_id:pending.request_id,approval_id:pending.approval_id})});if(response.status==="executed"){pending=null;renderApproval();if(response.result?.items){cart=response.result;renderCart()}status("Exact action approved and executed once.","ok");await loadTraffic()}else status(response.reason||"Approval was refused","error")}
async function armFault(){const result=await api("/api/auteric/lab/faults/lost-write",{method:"POST",body:"{}"});status(result.warning,"error")}
async function changePrice(price){const result=await api("/api/auteric/lab/products/demo-shoes/price",{method:"PUT",body:JSON.stringify({price})});status(`Shoes price changed from $${result.previous} to $${result.price} in the synthetic merchant.`,"ok");await loadProducts()}
async function reconcile(){if(!lastUnknownRequestId)return;const result=await api(`/api/auteric/reconcile/${encodeURIComponent(lastUnknownRequestId)}`);const observed=result.observed_cart?` Fresh cart total: $${result.observed_cart.total}.`:"";status(`${result.status}: ${result.guidance||"No gateway record."}${observed} ${result.evidence_limit||""}`,result.status==="confirmed"?"ok":"error")}
async function loadTraffic(){const response=await api("/api/auteric/traffic");const root=$("traffic");root.textContent="";for(const row of response.traffic.slice(0,12)){const tr=document.createElement("tr");for(const value of [row.operation,row.state,row.decision?.outcome||"—",row.latency?`${Math.round(row.latency)} ms`:"—"]){const td=document.createElement("td");td.textContent=value;if(value===row.state)td.className="state";tr.append(td)}root.append(tr)}}
async function init(){try{window.autericLabBootstrap??=api("/api/auteric/bootstrap");const config=await window.autericLabBootstrap;csrf=config.csrf;window.dispatchEvent(new CustomEvent("auteric-lab-ready",{detail:config}));status("Unique local agent session ready.","ok");await Promise.all([loadProducts(),loadTraffic()])}catch(error){status(error.message,"error")}}
window.addEventListener("auteric-gateway-outcome",event=>{const detail=event.detail||{};applyOutcome(detail,detail.operation,detail.input,detail.request_id);run(loadTraffic)()});
$("refresh").addEventListener("click",run(loadProducts));$("create-cart").addEventListener("click",run(createCart));$("checkout").addEventListener("click",run(checkout));$("traffic-refresh").addEventListener("click",run(loadTraffic));$("arm-fault").addEventListener("click",run(armFault));$("price-up").addEventListener("click",run(()=>changePrice("120.00")));$("price-reset").addEventListener("click",run(()=>changePrice("100.00")));$("reconcile").addEventListener("click",run(reconcile));run(init)();
