// Harness files the acceptance runner writes into the temporary workspace
// copy (never into the merchant source). They boot the merchant's generated
// composition root with the dev installation/trust the runner minted, on a
// loopback port, environment=dev (MEP/1 §4). Cleanup removes only this
// harness directory; the merchant tree is a throwaway copy.

export const HARNESS_DIR = '.auteric/acceptance';

export const SERVER_MJS = `// Acceptance harness server (generated by the Auteric acceptance runner).
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const root = process.env.AUTERIC_ACCEPTANCE_ROOT;
const runtime = JSON.parse(readFileSync(join(root, '${HARNESS_DIR}/dev-runtime.json'), 'utf8'));
const { createAutericApp } = await import(pathToFileURL(join(root, runtime.composition_root)).href);

const app = createAutericApp({}, {
  installation: runtime.installation,
  trust: runtime.trust,
  principals: runtime.principals,
  storeId: runtime.installation.storeId,
  hostname: runtime.hostname,
  discoveryFetcher: { async fetch() { throw new Error('discovery is not exercised by the acceptance harness'); } },
});

const server = app.listen(runtime.port, '127.0.0.1', () => {
  console.log('auteric-acceptance-ready ' + JSON.stringify({ port: server.address().port }));
});
process.on('SIGTERM', () => server.close(() => process.exit(0)));
setTimeout(() => { console.error('acceptance harness watchdog: forcing exit'); process.exit(3); }, 180000).unref();
`;

// The generated composition root imports its adapters with a ".js" specifier
// (TypeScript convention) while the files on disk are ".ts". Under Node's type
// stripping there is no compile step, so this hook redirects to the ".ts" file
// when no ".js" file exists. Binding output is served byte-identical.
export const TS_RESOLVE_HOOK_MJS = `import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export async function resolve(specifier, context, nextResolve) {
  if ((specifier.startsWith('./') || specifier.startsWith('../')) && specifier.endsWith('.js') && context.parentURL?.startsWith('file:')) {
    const candidate = new URL(specifier.slice(0, -3) + '.ts', context.parentURL);
    try {
      if (!existsSync(fileURLToPath(new URL(specifier, context.parentURL))) && existsSync(fileURLToPath(candidate))) {
        return { url: candidate.href, shortCircuit: true };
      }
    } catch { /* fall through to the default resolver */ }
  }
  return nextResolve(specifier, context);
}
`;

export const REGISTER_HOOK_MJS = `import { register } from 'node:module';
register('./ts-resolve-hook.mjs', import.meta.url);
`;
