# Vendored copy of packages/commerce-contracts/generated/python/auteric_contracts/__init__.py
# Regenerate with: python packages/merchant-python/tools/sync_contracts.py
# Do not edit by hand.
"""Generated by packages/commerce-contracts/tools/compile.py --emit. Do not edit.

Dependency-free validators for the Auteric merchant commerce contracts
(registry 1.0.0, merchant_protocol "1").
"""
import re
from typing import Any, NotRequired, TypedDict

REGISTRY_DIGEST = "sha256:671bd2cb706dd60773de5fdecbe5d35a5822a0d33fafdcfb92f62ddd33134c0c"
REGISTRY_VERSION = "1.0.0"
MERCHANT_PROTOCOL = "1"

ERROR_INVALID_INPUT = "INVALID_INPUT"


class ContractValidationError(ValueError):
    """A payload violates an Auteric commerce contract.

    category is one of: invalid_type, missing_required, unknown_field,
    invalid_value. All categories map to the MEP/1 wire code INVALID_INPUT.
    """

    def __init__(self, category, path, message):
        super().__init__(f"{category} at {path}: {message}")
        self.category = category
        self.path = path


CURRENCY_TABLE_VERSION = "iso4217:2015-amendment-174"
DEFAULT_CURRENCY_EXPONENT = 2
CURRENCY_EXPONENTS = {
    "BHD": 3,
    "BIF": 0,
    "CLP": 0,
    "DJF": 0,
    "GNF": 0,
    "IQD": 3,
    "JOD": 3,
    "JPY": 0,
    "KMF": 0,
    "KRW": 0,
    "KWD": 3,
    "LYD": 3,
    "OMR": 3,
    "PYG": 0,
    "RWF": 0,
    "TND": 3,
    "UGX": 0,
    "VND": 0,
    "VUV": 0,
    "XAF": 0,
    "XOF": 0,
    "XPF": 0,
}


IdsActionId = str


IdsBuyerPrincipalId = str


IdsCartId = str


IdsCheckoutId = str


IdsCursor = str


IdsDiscountCode = str


IdsLineId = str


IdsOrderId = str


IdsPrincipalId = str


IdsProductId = str


IdsShippingOptionId = str


IdsVariantId = str


class AddToCartInput(TypedDict):
    expected_revision: NotRequired[int]
    product_id: IdsProductId
    quantity: int
    variant_id: NotRequired[IdsVariantId]


class Address(TypedDict):
    city: str
    country_code: str
    line1: str
    line2: NotRequired[str]
    phone: NotRequired[str]
    postal_code: str
    recipient_name: NotRequired[str]
    region: NotRequired[str]


class ApplyDiscountCodeInput(TypedDict):
    code: IdsDiscountCode
    expected_revision: NotRequired[int]


class CancelCartInput(TypedDict):
    expected_revision: NotRequired[int]
    reason: NotRequired[str]


class CancelCheckoutInput(TypedDict):
    expected_revision: NotRequired[int]
    reason: NotRequired[str]


class CheckoutPayment(TypedDict):
    handler: NotRequired[str]
    status: str


class CompleteCheckoutInputPayment(TypedDict):
    handler: str
    token: str


class CreateCheckoutInput(TypedDict):
    buyer_principal: NotRequired[IdsPrincipalId]
    cart_id: IdsCartId
    expected_cart_revision: NotRequired[int]


class ErrorError(TypedDict):
    action_id: IdsActionId
    code: str
    details: NotRequired[dict[str, Any]]
    message: str
    retryable: bool


class GetCartInput(TypedDict):
    pass


class GetCheckoutInput(TypedDict):
    pass


class GetOrderInput(TypedDict):
    pass


class GetProductInput(TypedDict):
    pass


class GetShippingOptionsInput(TypedDict):
    currency: NotRequired[str]


class LineItemInput(TypedDict):
    product_id: IdsProductId
    quantity: int
    variant_id: NotRequired[IdsVariantId]


class Money(TypedDict):
    amount_minor: int
    currency: str


class Pagination(TypedDict):
    has_more: bool
    next_cursor: NotRequired[IdsCursor]


class RemoveDiscountCodeInput(TypedDict):
    expected_revision: NotRequired[int]


class RemoveFromCartInput(TypedDict):
    expected_revision: NotRequired[int]


class SearchProductsInput(TypedDict):
    category: NotRequired[str]
    currency: NotRequired[str]
    cursor: NotRequired[IdsCursor]
    limit: NotRequired[int]
    price_max_minor: NotRequired[int]
    price_min_minor: NotRequired[int]
    q: str


class SelectShippingOptionInput(TypedDict):
    expected_revision: NotRequired[int]
    option_id: IdsShippingOptionId


class UpdateCartItemInput(TypedDict):
    expected_revision: NotRequired[int]
    quantity: int


class CompleteCheckoutInput(TypedDict):
    expected_revision: NotRequired[int]
    payment: CompleteCheckoutInputPayment


class CreateCartInput(TypedDict):
    currency: str
    line_items: NotRequired[list[LineItemInput]]


class Discount(TypedDict):
    amount: Money
    code: IdsDiscountCode
    description: NotRequired[str]
    kind: str


class Error(TypedDict):
    error: ErrorError


class LineItem(TypedDict):
    line_id: IdsLineId
    product_id: IdsProductId
    quantity: int
    title: str
    total_price: Money
    unit_price: Money
    variant_id: NotRequired[IdsVariantId]


class ProductVariantsItem(TypedDict):
    available: bool
    price: Money
    title: NotRequired[str]
    variant_id: IdsVariantId


class ReplaceCartItemsInput(TypedDict):
    expected_revision: NotRequired[int]
    items: list[LineItemInput]


class SetShippingAddressInput(TypedDict):
    address: Address
    expected_revision: NotRequired[int]


class ShippingOption(TypedDict):
    carrier: NotRequired[str]
    eta_days_max: NotRequired[int]
    eta_days_min: NotRequired[int]
    label: str
    option_id: IdsShippingOptionId
    price: Money


class UpdateCheckoutInput(TypedDict):
    buyer_principal: NotRequired[IdsPrincipalId]
    expected_revision: NotRequired[int]
    shipping_address: NotRequired[Address]


class Cart(TypedDict):
    cart_id: IdsCartId
    currency: str
    discount_total: Money
    discounts: list[Discount]
    line_items: list[LineItem]
    resource_revision: int
    status: str
    subtotal: Money
    total: Money


class Checkout(TypedDict):
    buyer_principal: NotRequired[IdsPrincipalId]
    cart_id: IdsCartId
    checkout_id: IdsCheckoutId
    discount_total: Money
    payment: CheckoutPayment
    resource_revision: int
    shipping_address: NotRequired[Address]
    shipping_option: NotRequired[ShippingOption]
    shipping_total: Money
    status: str
    subtotal: Money
    tax_total: Money
    total: Money


class GetShippingOptionsOutput(TypedDict):
    options: list[ShippingOption]


class Order(TypedDict):
    buyer_principal: IdsBuyerPrincipalId
    cart_id: IdsCartId
    checkout_id: IdsCheckoutId
    created_at: str
    discount_total: Money
    discounts: list[Discount]
    line_items: list[LineItem]
    order_id: IdsOrderId
    shipping_address: Address
    shipping_option: ShippingOption
    shipping_total: Money
    status: str
    subtotal: Money
    tax_total: Money
    total: Money


class Product(TypedDict):
    description: NotRequired[str]
    product_id: IdsProductId
    tags: NotRequired[list[str]]
    title: str
    variants: list[ProductVariantsItem]
    vendor: NotRequired[str]


class CompleteCheckoutOutput(TypedDict):
    order: Order


class SearchProductsOutput(TypedDict):
    page: Pagination
    results: list[Product]


AddToCartOutput = Cart


ApplyDiscountCodeOutput = Cart


CancelCartOutput = Cart


CancelCheckoutOutput = Checkout


CreateCartOutput = Cart


CreateCheckoutOutput = Checkout


GetCartOutput = Cart


GetCheckoutOutput = Checkout


GetOrderOutput = Order


GetProductOutput = Product


RemoveDiscountCodeOutput = Cart


RemoveFromCartOutput = Cart


ReplaceCartItemsOutput = Cart


SelectShippingOptionOutput = Checkout


SetShippingAddressOutput = Checkout


UpdateCartItemOutput = Cart


UpdateCheckoutOutput = Checkout


_RE_0 = re.compile("[A-Z]{2}")
_RE_1 = re.compile("[+0-9][0-9 -]{4,30}")
_RE_2 = re.compile("[A-Z]{3}")
_RE_3 = re.compile("action_[A-Za-z0-9]{8,64}")
_RE_4 = re.compile("buyer_[A-Za-z0-9]{8,64}")
_RE_5 = re.compile("cart_[A-Za-z0-9]{8,64}")
_RE_6 = re.compile("chk_[A-Za-z0-9]{8,64}")
_RE_7 = re.compile("[A-Za-z0-9_-]{1,256}")
_RE_8 = re.compile("[A-Z0-9][A-Z0-9_-]{2,31}")
_RE_9 = re.compile("line_[A-Za-z0-9]{8,64}")
_RE_10 = re.compile("ord_[A-Za-z0-9]{8,64}")
_RE_11 = re.compile("(buyer|guest)_[A-Za-z0-9]{8,64}")
_RE_12 = re.compile("prod_[A-Za-z0-9]{8,64}")
_RE_13 = re.compile("opt_[A-Za-z0-9]{3,64}")
_RE_14 = re.compile("var_[A-Za-z0-9]{8,64}")
_RE_15 = re.compile("[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z")


def validate_add_to_cart_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("expected_revision", "product_id", "quantity", "variant_id",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "product_id" not in value:
        raise ContractValidationError("missing_required", path + ".product_id", "missing required field")
    if "quantity" not in value:
        raise ContractValidationError("missing_required", path + ".quantity", "missing required field")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")
    validate_ids_product_id(value["product_id"], path + ".product_id")
    if not isinstance(value["quantity"], int) or isinstance(value["quantity"], bool):
        raise ContractValidationError("invalid_type", path + ".quantity", "expected integer")
    if value["quantity"] < 1:
        raise ContractValidationError("invalid_value", path + ".quantity", "below minimum 1")
    if value["quantity"] > 999:
        raise ContractValidationError("invalid_value", path + ".quantity", "above maximum 999")
    if "variant_id" in value:
        validate_ids_variant_id(value["variant_id"], path + ".variant_id")


def validate_add_to_cart_output(value, path="$"):
    validate_cart(value, path)


def validate_address(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("city", "country_code", "line1", "line2", "phone", "postal_code", "recipient_name", "region",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "line1" not in value:
        raise ContractValidationError("missing_required", path + ".line1", "missing required field")
    if "city" not in value:
        raise ContractValidationError("missing_required", path + ".city", "missing required field")
    if "postal_code" not in value:
        raise ContractValidationError("missing_required", path + ".postal_code", "missing required field")
    if "country_code" not in value:
        raise ContractValidationError("missing_required", path + ".country_code", "missing required field")
    if not isinstance(value["city"], str):
        raise ContractValidationError("invalid_type", path + ".city", "expected string")
    if len(value["city"]) < 1:
        raise ContractValidationError("invalid_value", path + ".city", "shorter than minLength 1")
    if len(value["city"]) > 100:
        raise ContractValidationError("invalid_value", path + ".city", "longer than maxLength 100")
    if not isinstance(value["country_code"], str):
        raise ContractValidationError("invalid_type", path + ".country_code", "expected string")
    if not _RE_0.fullmatch(value["country_code"]):
        raise ContractValidationError("invalid_value", path + ".country_code", "does not match pattern ^[A-Z]{2}$")
    if not isinstance(value["line1"], str):
        raise ContractValidationError("invalid_type", path + ".line1", "expected string")
    if len(value["line1"]) < 1:
        raise ContractValidationError("invalid_value", path + ".line1", "shorter than minLength 1")
    if len(value["line1"]) > 200:
        raise ContractValidationError("invalid_value", path + ".line1", "longer than maxLength 200")
    if "line2" in value:
        if not isinstance(value["line2"], str):
            raise ContractValidationError("invalid_type", path + ".line2", "expected string")
        if len(value["line2"]) < 1:
            raise ContractValidationError("invalid_value", path + ".line2", "shorter than minLength 1")
        if len(value["line2"]) > 200:
            raise ContractValidationError("invalid_value", path + ".line2", "longer than maxLength 200")
    if "phone" in value:
        if not isinstance(value["phone"], str):
            raise ContractValidationError("invalid_type", path + ".phone", "expected string")
        if not _RE_1.fullmatch(value["phone"]):
            raise ContractValidationError("invalid_value", path + ".phone", "does not match pattern ^[+0-9][0-9 -]{4,30}$")
    if not isinstance(value["postal_code"], str):
        raise ContractValidationError("invalid_type", path + ".postal_code", "expected string")
    if len(value["postal_code"]) < 1:
        raise ContractValidationError("invalid_value", path + ".postal_code", "shorter than minLength 1")
    if len(value["postal_code"]) > 20:
        raise ContractValidationError("invalid_value", path + ".postal_code", "longer than maxLength 20")
    if "recipient_name" in value:
        if not isinstance(value["recipient_name"], str):
            raise ContractValidationError("invalid_type", path + ".recipient_name", "expected string")
        if len(value["recipient_name"]) < 1:
            raise ContractValidationError("invalid_value", path + ".recipient_name", "shorter than minLength 1")
        if len(value["recipient_name"]) > 100:
            raise ContractValidationError("invalid_value", path + ".recipient_name", "longer than maxLength 100")
    if "region" in value:
        if not isinstance(value["region"], str):
            raise ContractValidationError("invalid_type", path + ".region", "expected string")
        if len(value["region"]) < 1:
            raise ContractValidationError("invalid_value", path + ".region", "shorter than minLength 1")
        if len(value["region"]) > 100:
            raise ContractValidationError("invalid_value", path + ".region", "longer than maxLength 100")


def validate_apply_discount_code_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("code", "expected_revision",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "code" not in value:
        raise ContractValidationError("missing_required", path + ".code", "missing required field")
    validate_ids_discount_code(value["code"], path + ".code")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")


def validate_apply_discount_code_output(value, path="$"):
    validate_cart(value, path)


def validate_cancel_cart_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("expected_revision", "reason",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")
    if "reason" in value:
        if not isinstance(value["reason"], str):
            raise ContractValidationError("invalid_type", path + ".reason", "expected string")
        if len(value["reason"]) < 1:
            raise ContractValidationError("invalid_value", path + ".reason", "shorter than minLength 1")
        if len(value["reason"]) > 500:
            raise ContractValidationError("invalid_value", path + ".reason", "longer than maxLength 500")


def validate_cancel_cart_output(value, path="$"):
    validate_cart(value, path)


def validate_cancel_checkout_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("expected_revision", "reason",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")
    if "reason" in value:
        if not isinstance(value["reason"], str):
            raise ContractValidationError("invalid_type", path + ".reason", "expected string")
        if len(value["reason"]) < 1:
            raise ContractValidationError("invalid_value", path + ".reason", "shorter than minLength 1")
        if len(value["reason"]) > 500:
            raise ContractValidationError("invalid_value", path + ".reason", "longer than maxLength 500")


def validate_cancel_checkout_output(value, path="$"):
    validate_checkout(value, path)


def validate_cart(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("cart_id", "currency", "discount_total", "discounts", "line_items", "resource_revision", "status", "subtotal", "total",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "cart_id" not in value:
        raise ContractValidationError("missing_required", path + ".cart_id", "missing required field")
    if "resource_revision" not in value:
        raise ContractValidationError("missing_required", path + ".resource_revision", "missing required field")
    if "status" not in value:
        raise ContractValidationError("missing_required", path + ".status", "missing required field")
    if "currency" not in value:
        raise ContractValidationError("missing_required", path + ".currency", "missing required field")
    if "line_items" not in value:
        raise ContractValidationError("missing_required", path + ".line_items", "missing required field")
    if "discounts" not in value:
        raise ContractValidationError("missing_required", path + ".discounts", "missing required field")
    if "subtotal" not in value:
        raise ContractValidationError("missing_required", path + ".subtotal", "missing required field")
    if "discount_total" not in value:
        raise ContractValidationError("missing_required", path + ".discount_total", "missing required field")
    if "total" not in value:
        raise ContractValidationError("missing_required", path + ".total", "missing required field")
    validate_ids_cart_id(value["cart_id"], path + ".cart_id")
    if not isinstance(value["currency"], str):
        raise ContractValidationError("invalid_type", path + ".currency", "expected string")
    if not _RE_2.fullmatch(value["currency"]):
        raise ContractValidationError("invalid_value", path + ".currency", "does not match pattern ^[A-Z]{3}$")
    validate_money(value["discount_total"], path + ".discount_total")
    if not isinstance(value["discounts"], list):
        raise ContractValidationError("invalid_type", path + ".discounts", "expected array")
    if len(value["discounts"]) < 0:
        raise ContractValidationError("invalid_value", path + ".discounts", "fewer than minItems 0")
    if len(value["discounts"]) > 20:
        raise ContractValidationError("invalid_value", path + ".discounts", "more than maxItems 20")
    for _i1, _v1 in enumerate(value["discounts"]):
        validate_discount(_v1, path + ".discounts" + "[" + str(_i1) + "]")
    if not isinstance(value["line_items"], list):
        raise ContractValidationError("invalid_type", path + ".line_items", "expected array")
    if len(value["line_items"]) < 0:
        raise ContractValidationError("invalid_value", path + ".line_items", "fewer than minItems 0")
    if len(value["line_items"]) > 200:
        raise ContractValidationError("invalid_value", path + ".line_items", "more than maxItems 200")
    for _i1, _v1 in enumerate(value["line_items"]):
        validate_line_item(_v1, path + ".line_items" + "[" + str(_i1) + "]")
    if not isinstance(value["resource_revision"], int) or isinstance(value["resource_revision"], bool):
        raise ContractValidationError("invalid_type", path + ".resource_revision", "expected integer")
    if value["resource_revision"] < 0:
        raise ContractValidationError("invalid_value", path + ".resource_revision", "below minimum 0")
    if not isinstance(value["status"], str):
        raise ContractValidationError("invalid_type", path + ".status", "expected string")
    if value["status"] not in ("active", "cancelled", "converted",):
        raise ContractValidationError("invalid_value", path + ".status", "not an allowed value")
    validate_money(value["subtotal"], path + ".subtotal")
    validate_money(value["total"], path + ".total")


def validate_checkout(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("buyer_principal", "cart_id", "checkout_id", "discount_total", "payment", "resource_revision", "shipping_address", "shipping_option", "shipping_total", "status", "subtotal", "tax_total", "total",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "checkout_id" not in value:
        raise ContractValidationError("missing_required", path + ".checkout_id", "missing required field")
    if "cart_id" not in value:
        raise ContractValidationError("missing_required", path + ".cart_id", "missing required field")
    if "resource_revision" not in value:
        raise ContractValidationError("missing_required", path + ".resource_revision", "missing required field")
    if "status" not in value:
        raise ContractValidationError("missing_required", path + ".status", "missing required field")
    if "subtotal" not in value:
        raise ContractValidationError("missing_required", path + ".subtotal", "missing required field")
    if "discount_total" not in value:
        raise ContractValidationError("missing_required", path + ".discount_total", "missing required field")
    if "shipping_total" not in value:
        raise ContractValidationError("missing_required", path + ".shipping_total", "missing required field")
    if "tax_total" not in value:
        raise ContractValidationError("missing_required", path + ".tax_total", "missing required field")
    if "total" not in value:
        raise ContractValidationError("missing_required", path + ".total", "missing required field")
    if "payment" not in value:
        raise ContractValidationError("missing_required", path + ".payment", "missing required field")
    if "buyer_principal" in value:
        validate_ids_principal_id(value["buyer_principal"], path + ".buyer_principal")
    validate_ids_cart_id(value["cart_id"], path + ".cart_id")
    validate_ids_checkout_id(value["checkout_id"], path + ".checkout_id")
    validate_money(value["discount_total"], path + ".discount_total")
    if not isinstance(value["payment"], dict):
        raise ContractValidationError("invalid_type", path + ".payment", "expected object")
    _allowed1 = frozenset(("handler", "status",))
    for _k1 in sorted(value["payment"]):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + ".payment" + "." + _k1, "unknown field")
    if "status" not in value["payment"]:
        raise ContractValidationError("missing_required", path + ".payment" + ".status", "missing required field")
    if "handler" in value["payment"]:
        if not isinstance(value["payment"]["handler"], str):
            raise ContractValidationError("invalid_type", path + ".payment" + ".handler", "expected string")
        if len(value["payment"]["handler"]) < 1:
            raise ContractValidationError("invalid_value", path + ".payment" + ".handler", "shorter than minLength 1")
        if len(value["payment"]["handler"]) > 64:
            raise ContractValidationError("invalid_value", path + ".payment" + ".handler", "longer than maxLength 64")
    if not isinstance(value["payment"]["status"], str):
        raise ContractValidationError("invalid_type", path + ".payment" + ".status", "expected string")
    if value["payment"]["status"] not in ("authorized", "failed", "not_started", "paid", "pending",):
        raise ContractValidationError("invalid_value", path + ".payment" + ".status", "not an allowed value")
    if not isinstance(value["resource_revision"], int) or isinstance(value["resource_revision"], bool):
        raise ContractValidationError("invalid_type", path + ".resource_revision", "expected integer")
    if value["resource_revision"] < 0:
        raise ContractValidationError("invalid_value", path + ".resource_revision", "below minimum 0")
    if "shipping_address" in value:
        validate_address(value["shipping_address"], path + ".shipping_address")
    if "shipping_option" in value:
        validate_shipping_option(value["shipping_option"], path + ".shipping_option")
    validate_money(value["shipping_total"], path + ".shipping_total")
    if not isinstance(value["status"], str):
        raise ContractValidationError("invalid_type", path + ".status", "expected string")
    if value["status"] not in ("cancelled", "completed", "completing", "payment_pending", "pending", "ready",):
        raise ContractValidationError("invalid_value", path + ".status", "not an allowed value")
    validate_money(value["subtotal"], path + ".subtotal")
    validate_money(value["tax_total"], path + ".tax_total")
    validate_money(value["total"], path + ".total")


def validate_complete_checkout_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("expected_revision", "payment",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "payment" not in value:
        raise ContractValidationError("missing_required", path + ".payment", "missing required field")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")
    if not isinstance(value["payment"], dict):
        raise ContractValidationError("invalid_type", path + ".payment", "expected object")
    _allowed1 = frozenset(("handler", "token",))
    for _k1 in sorted(value["payment"]):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + ".payment" + "." + _k1, "unknown field")
    if "handler" not in value["payment"]:
        raise ContractValidationError("missing_required", path + ".payment" + ".handler", "missing required field")
    if "token" not in value["payment"]:
        raise ContractValidationError("missing_required", path + ".payment" + ".token", "missing required field")
    if not isinstance(value["payment"]["handler"], str):
        raise ContractValidationError("invalid_type", path + ".payment" + ".handler", "expected string")
    if len(value["payment"]["handler"]) < 1:
        raise ContractValidationError("invalid_value", path + ".payment" + ".handler", "shorter than minLength 1")
    if len(value["payment"]["handler"]) > 64:
        raise ContractValidationError("invalid_value", path + ".payment" + ".handler", "longer than maxLength 64")
    if not isinstance(value["payment"]["token"], str):
        raise ContractValidationError("invalid_type", path + ".payment" + ".token", "expected string")
    if len(value["payment"]["token"]) < 1:
        raise ContractValidationError("invalid_value", path + ".payment" + ".token", "shorter than minLength 1")
    if len(value["payment"]["token"]) > 4096:
        raise ContractValidationError("invalid_value", path + ".payment" + ".token", "longer than maxLength 4096")


def validate_complete_checkout_output(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("order",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "order" not in value:
        raise ContractValidationError("missing_required", path + ".order", "missing required field")
    validate_order(value["order"], path + ".order")


def validate_create_cart_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("currency", "line_items",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "currency" not in value:
        raise ContractValidationError("missing_required", path + ".currency", "missing required field")
    if not isinstance(value["currency"], str):
        raise ContractValidationError("invalid_type", path + ".currency", "expected string")
    if not _RE_2.fullmatch(value["currency"]):
        raise ContractValidationError("invalid_value", path + ".currency", "does not match pattern ^[A-Z]{3}$")
    if "line_items" in value:
        if not isinstance(value["line_items"], list):
            raise ContractValidationError("invalid_type", path + ".line_items", "expected array")
        if len(value["line_items"]) < 0:
            raise ContractValidationError("invalid_value", path + ".line_items", "fewer than minItems 0")
        if len(value["line_items"]) > 200:
            raise ContractValidationError("invalid_value", path + ".line_items", "more than maxItems 200")
        for _i2, _v2 in enumerate(value["line_items"]):
            validate_line_item_input(_v2, path + ".line_items" + "[" + str(_i2) + "]")


def validate_create_cart_output(value, path="$"):
    validate_cart(value, path)


def validate_create_checkout_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("buyer_principal", "cart_id", "expected_cart_revision",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "cart_id" not in value:
        raise ContractValidationError("missing_required", path + ".cart_id", "missing required field")
    if "buyer_principal" in value:
        validate_ids_principal_id(value["buyer_principal"], path + ".buyer_principal")
    validate_ids_cart_id(value["cart_id"], path + ".cart_id")
    if "expected_cart_revision" in value:
        if not isinstance(value["expected_cart_revision"], int) or isinstance(value["expected_cart_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_cart_revision", "expected integer")
        if value["expected_cart_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_cart_revision", "below minimum 0")


def validate_create_checkout_output(value, path="$"):
    validate_checkout(value, path)


def validate_discount(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("amount", "code", "description", "kind",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "code" not in value:
        raise ContractValidationError("missing_required", path + ".code", "missing required field")
    if "kind" not in value:
        raise ContractValidationError("missing_required", path + ".kind", "missing required field")
    if "amount" not in value:
        raise ContractValidationError("missing_required", path + ".amount", "missing required field")
    validate_money(value["amount"], path + ".amount")
    validate_ids_discount_code(value["code"], path + ".code")
    if "description" in value:
        if not isinstance(value["description"], str):
            raise ContractValidationError("invalid_type", path + ".description", "expected string")
        if len(value["description"]) < 0:
            raise ContractValidationError("invalid_value", path + ".description", "shorter than minLength 0")
        if len(value["description"]) > 200:
            raise ContractValidationError("invalid_value", path + ".description", "longer than maxLength 200")
    if not isinstance(value["kind"], str):
        raise ContractValidationError("invalid_type", path + ".kind", "expected string")
    if value["kind"] not in ("fixed_amount", "free_shipping", "percentage",):
        raise ContractValidationError("invalid_value", path + ".kind", "not an allowed value")


def validate_error(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("error",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "error" not in value:
        raise ContractValidationError("missing_required", path + ".error", "missing required field")
    if not isinstance(value["error"], dict):
        raise ContractValidationError("invalid_type", path + ".error", "expected object")
    _allowed1 = frozenset(("action_id", "code", "details", "message", "retryable",))
    for _k1 in sorted(value["error"]):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + ".error" + "." + _k1, "unknown field")
    if "code" not in value["error"]:
        raise ContractValidationError("missing_required", path + ".error" + ".code", "missing required field")
    if "message" not in value["error"]:
        raise ContractValidationError("missing_required", path + ".error" + ".message", "missing required field")
    if "retryable" not in value["error"]:
        raise ContractValidationError("missing_required", path + ".error" + ".retryable", "missing required field")
    if "action_id" not in value["error"]:
        raise ContractValidationError("missing_required", path + ".error" + ".action_id", "missing required field")
    validate_ids_action_id(value["error"]["action_id"], path + ".error" + ".action_id")
    if not isinstance(value["error"]["code"], str):
        raise ContractValidationError("invalid_type", path + ".error" + ".code", "expected string")
    if value["error"]["code"] not in ("CAPABILITY_DISABLED", "CONTRACT_MISMATCH", "EXECUTION_UNCERTAIN", "FORBIDDEN", "IDEMPOTENCY_CONFLICT", "INVALID_INPUT", "OUT_OF_STOCK", "PAYMENT_PENDING", "RATE_LIMITED", "RESOURCE_NOT_FOUND", "REVISION_CONFLICT", "SSRF_BLOCKED", "UNAUTHENTICATED", "UPSTREAM_ERROR",):
        raise ContractValidationError("invalid_value", path + ".error" + ".code", "not an allowed value")
    if "details" in value["error"]:
        if not isinstance(value["error"]["details"], dict):
            raise ContractValidationError("invalid_type", path + ".error" + ".details", "expected object")
    if not isinstance(value["error"]["message"], str):
        raise ContractValidationError("invalid_type", path + ".error" + ".message", "expected string")
    if len(value["error"]["message"]) < 1:
        raise ContractValidationError("invalid_value", path + ".error" + ".message", "shorter than minLength 1")
    if len(value["error"]["message"]) > 500:
        raise ContractValidationError("invalid_value", path + ".error" + ".message", "longer than maxLength 500")
    if not isinstance(value["error"]["retryable"], bool):
        raise ContractValidationError("invalid_type", path + ".error" + ".retryable", "expected boolean")


def validate_get_cart_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset()
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")


def validate_get_cart_output(value, path="$"):
    validate_cart(value, path)


def validate_get_checkout_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset()
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")


def validate_get_checkout_output(value, path="$"):
    validate_checkout(value, path)


def validate_get_order_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset()
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")


def validate_get_order_output(value, path="$"):
    validate_order(value, path)


def validate_get_product_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset()
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")


def validate_get_product_output(value, path="$"):
    validate_product(value, path)


def validate_get_shipping_options_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("currency",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "currency" in value:
        if not isinstance(value["currency"], str):
            raise ContractValidationError("invalid_type", path + ".currency", "expected string")
        if not _RE_2.fullmatch(value["currency"]):
            raise ContractValidationError("invalid_value", path + ".currency", "does not match pattern ^[A-Z]{3}$")


def validate_get_shipping_options_output(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("options",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "options" not in value:
        raise ContractValidationError("missing_required", path + ".options", "missing required field")
    if not isinstance(value["options"], list):
        raise ContractValidationError("invalid_type", path + ".options", "expected array")
    if len(value["options"]) < 0:
        raise ContractValidationError("invalid_value", path + ".options", "fewer than minItems 0")
    if len(value["options"]) > 50:
        raise ContractValidationError("invalid_value", path + ".options", "more than maxItems 50")
    for _i1, _v1 in enumerate(value["options"]):
        validate_shipping_option(_v1, path + ".options" + "[" + str(_i1) + "]")


def validate_ids_action_id(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_3.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^action_[A-Za-z0-9]{8,64}$")


def validate_ids_buyer_principal_id(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_4.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^buyer_[A-Za-z0-9]{8,64}$")


def validate_ids_cart_id(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_5.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^cart_[A-Za-z0-9]{8,64}$")


def validate_ids_checkout_id(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_6.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^chk_[A-Za-z0-9]{8,64}$")


def validate_ids_cursor(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_7.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^[A-Za-z0-9_-]{1,256}$")


def validate_ids_discount_code(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_8.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^[A-Z0-9][A-Z0-9_-]{2,31}$")


def validate_ids_line_id(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_9.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^line_[A-Za-z0-9]{8,64}$")


def validate_ids_order_id(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_10.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^ord_[A-Za-z0-9]{8,64}$")


def validate_ids_principal_id(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_11.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^(buyer|guest)_[A-Za-z0-9]{8,64}$")


def validate_ids_product_id(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_12.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^prod_[A-Za-z0-9]{8,64}$")


def validate_ids_shipping_option_id(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_13.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^opt_[A-Za-z0-9]{3,64}$")


def validate_ids_variant_id(value, path="$"):
    if not isinstance(value, str):
        raise ContractValidationError("invalid_type", path, "expected string")
    if not _RE_14.fullmatch(value):
        raise ContractValidationError("invalid_value", path, "does not match pattern ^var_[A-Za-z0-9]{8,64}$")


def validate_line_item(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("line_id", "product_id", "quantity", "title", "total_price", "unit_price", "variant_id",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "line_id" not in value:
        raise ContractValidationError("missing_required", path + ".line_id", "missing required field")
    if "product_id" not in value:
        raise ContractValidationError("missing_required", path + ".product_id", "missing required field")
    if "title" not in value:
        raise ContractValidationError("missing_required", path + ".title", "missing required field")
    if "quantity" not in value:
        raise ContractValidationError("missing_required", path + ".quantity", "missing required field")
    if "unit_price" not in value:
        raise ContractValidationError("missing_required", path + ".unit_price", "missing required field")
    if "total_price" not in value:
        raise ContractValidationError("missing_required", path + ".total_price", "missing required field")
    validate_ids_line_id(value["line_id"], path + ".line_id")
    validate_ids_product_id(value["product_id"], path + ".product_id")
    if not isinstance(value["quantity"], int) or isinstance(value["quantity"], bool):
        raise ContractValidationError("invalid_type", path + ".quantity", "expected integer")
    if value["quantity"] < 1:
        raise ContractValidationError("invalid_value", path + ".quantity", "below minimum 1")
    if value["quantity"] > 999:
        raise ContractValidationError("invalid_value", path + ".quantity", "above maximum 999")
    if not isinstance(value["title"], str):
        raise ContractValidationError("invalid_type", path + ".title", "expected string")
    if len(value["title"]) < 1:
        raise ContractValidationError("invalid_value", path + ".title", "shorter than minLength 1")
    if len(value["title"]) > 300:
        raise ContractValidationError("invalid_value", path + ".title", "longer than maxLength 300")
    validate_money(value["total_price"], path + ".total_price")
    validate_money(value["unit_price"], path + ".unit_price")
    if "variant_id" in value:
        validate_ids_variant_id(value["variant_id"], path + ".variant_id")


def validate_line_item_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("product_id", "quantity", "variant_id",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "product_id" not in value:
        raise ContractValidationError("missing_required", path + ".product_id", "missing required field")
    if "quantity" not in value:
        raise ContractValidationError("missing_required", path + ".quantity", "missing required field")
    validate_ids_product_id(value["product_id"], path + ".product_id")
    if not isinstance(value["quantity"], int) or isinstance(value["quantity"], bool):
        raise ContractValidationError("invalid_type", path + ".quantity", "expected integer")
    if value["quantity"] < 1:
        raise ContractValidationError("invalid_value", path + ".quantity", "below minimum 1")
    if value["quantity"] > 999:
        raise ContractValidationError("invalid_value", path + ".quantity", "above maximum 999")
    if "variant_id" in value:
        validate_ids_variant_id(value["variant_id"], path + ".variant_id")


def validate_money(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("amount_minor", "currency",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "amount_minor" not in value:
        raise ContractValidationError("missing_required", path + ".amount_minor", "missing required field")
    if "currency" not in value:
        raise ContractValidationError("missing_required", path + ".currency", "missing required field")
    if not isinstance(value["amount_minor"], int) or isinstance(value["amount_minor"], bool):
        raise ContractValidationError("invalid_type", path + ".amount_minor", "expected integer")
    if value["amount_minor"] < 0:
        raise ContractValidationError("invalid_value", path + ".amount_minor", "below minimum 0")
    if not isinstance(value["currency"], str):
        raise ContractValidationError("invalid_type", path + ".currency", "expected string")
    if not _RE_2.fullmatch(value["currency"]):
        raise ContractValidationError("invalid_value", path + ".currency", "does not match pattern ^[A-Z]{3}$")


def validate_order(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("buyer_principal", "cart_id", "checkout_id", "created_at", "discount_total", "discounts", "line_items", "order_id", "shipping_address", "shipping_option", "shipping_total", "status", "subtotal", "tax_total", "total",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "order_id" not in value:
        raise ContractValidationError("missing_required", path + ".order_id", "missing required field")
    if "checkout_id" not in value:
        raise ContractValidationError("missing_required", path + ".checkout_id", "missing required field")
    if "cart_id" not in value:
        raise ContractValidationError("missing_required", path + ".cart_id", "missing required field")
    if "buyer_principal" not in value:
        raise ContractValidationError("missing_required", path + ".buyer_principal", "missing required field")
    if "status" not in value:
        raise ContractValidationError("missing_required", path + ".status", "missing required field")
    if "line_items" not in value:
        raise ContractValidationError("missing_required", path + ".line_items", "missing required field")
    if "discounts" not in value:
        raise ContractValidationError("missing_required", path + ".discounts", "missing required field")
    if "subtotal" not in value:
        raise ContractValidationError("missing_required", path + ".subtotal", "missing required field")
    if "discount_total" not in value:
        raise ContractValidationError("missing_required", path + ".discount_total", "missing required field")
    if "shipping_total" not in value:
        raise ContractValidationError("missing_required", path + ".shipping_total", "missing required field")
    if "tax_total" not in value:
        raise ContractValidationError("missing_required", path + ".tax_total", "missing required field")
    if "total" not in value:
        raise ContractValidationError("missing_required", path + ".total", "missing required field")
    if "shipping_address" not in value:
        raise ContractValidationError("missing_required", path + ".shipping_address", "missing required field")
    if "shipping_option" not in value:
        raise ContractValidationError("missing_required", path + ".shipping_option", "missing required field")
    if "created_at" not in value:
        raise ContractValidationError("missing_required", path + ".created_at", "missing required field")
    validate_ids_buyer_principal_id(value["buyer_principal"], path + ".buyer_principal")
    validate_ids_cart_id(value["cart_id"], path + ".cart_id")
    validate_ids_checkout_id(value["checkout_id"], path + ".checkout_id")
    if not isinstance(value["created_at"], str):
        raise ContractValidationError("invalid_type", path + ".created_at", "expected string")
    if not _RE_15.fullmatch(value["created_at"]):
        raise ContractValidationError("invalid_value", path + ".created_at", "does not match pattern ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$")
    validate_money(value["discount_total"], path + ".discount_total")
    if not isinstance(value["discounts"], list):
        raise ContractValidationError("invalid_type", path + ".discounts", "expected array")
    if len(value["discounts"]) < 0:
        raise ContractValidationError("invalid_value", path + ".discounts", "fewer than minItems 0")
    if len(value["discounts"]) > 20:
        raise ContractValidationError("invalid_value", path + ".discounts", "more than maxItems 20")
    for _i1, _v1 in enumerate(value["discounts"]):
        validate_discount(_v1, path + ".discounts" + "[" + str(_i1) + "]")
    if not isinstance(value["line_items"], list):
        raise ContractValidationError("invalid_type", path + ".line_items", "expected array")
    if len(value["line_items"]) < 0:
        raise ContractValidationError("invalid_value", path + ".line_items", "fewer than minItems 0")
    if len(value["line_items"]) > 200:
        raise ContractValidationError("invalid_value", path + ".line_items", "more than maxItems 200")
    for _i1, _v1 in enumerate(value["line_items"]):
        validate_line_item(_v1, path + ".line_items" + "[" + str(_i1) + "]")
    validate_ids_order_id(value["order_id"], path + ".order_id")
    validate_address(value["shipping_address"], path + ".shipping_address")
    validate_shipping_option(value["shipping_option"], path + ".shipping_option")
    validate_money(value["shipping_total"], path + ".shipping_total")
    if not isinstance(value["status"], str):
        raise ContractValidationError("invalid_type", path + ".status", "expected string")
    if value["status"] not in ("cancelled", "confirmed", "fulfilled",):
        raise ContractValidationError("invalid_value", path + ".status", "not an allowed value")
    validate_money(value["subtotal"], path + ".subtotal")
    validate_money(value["tax_total"], path + ".tax_total")
    validate_money(value["total"], path + ".total")


def validate_pagination(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("has_more", "next_cursor",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "has_more" not in value:
        raise ContractValidationError("missing_required", path + ".has_more", "missing required field")
    if not isinstance(value["has_more"], bool):
        raise ContractValidationError("invalid_type", path + ".has_more", "expected boolean")
    if "next_cursor" in value:
        validate_ids_cursor(value["next_cursor"], path + ".next_cursor")


def validate_product(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("description", "product_id", "tags", "title", "variants", "vendor",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "product_id" not in value:
        raise ContractValidationError("missing_required", path + ".product_id", "missing required field")
    if "title" not in value:
        raise ContractValidationError("missing_required", path + ".title", "missing required field")
    if "variants" not in value:
        raise ContractValidationError("missing_required", path + ".variants", "missing required field")
    if "description" in value:
        if not isinstance(value["description"], str):
            raise ContractValidationError("invalid_type", path + ".description", "expected string")
        if len(value["description"]) < 0:
            raise ContractValidationError("invalid_value", path + ".description", "shorter than minLength 0")
        if len(value["description"]) > 5000:
            raise ContractValidationError("invalid_value", path + ".description", "longer than maxLength 5000")
    validate_ids_product_id(value["product_id"], path + ".product_id")
    if "tags" in value:
        if not isinstance(value["tags"], list):
            raise ContractValidationError("invalid_type", path + ".tags", "expected array")
        if len(value["tags"]) < 0:
            raise ContractValidationError("invalid_value", path + ".tags", "fewer than minItems 0")
        if len(value["tags"]) > 50:
            raise ContractValidationError("invalid_value", path + ".tags", "more than maxItems 50")
        for _i2, _v2 in enumerate(value["tags"]):
            if not isinstance(_v2, str):
                raise ContractValidationError("invalid_type", path + ".tags" + "[" + str(_i2) + "]", "expected string")
            if len(_v2) < 1:
                raise ContractValidationError("invalid_value", path + ".tags" + "[" + str(_i2) + "]", "shorter than minLength 1")
            if len(_v2) > 64:
                raise ContractValidationError("invalid_value", path + ".tags" + "[" + str(_i2) + "]", "longer than maxLength 64")
    if not isinstance(value["title"], str):
        raise ContractValidationError("invalid_type", path + ".title", "expected string")
    if len(value["title"]) < 1:
        raise ContractValidationError("invalid_value", path + ".title", "shorter than minLength 1")
    if len(value["title"]) > 300:
        raise ContractValidationError("invalid_value", path + ".title", "longer than maxLength 300")
    if not isinstance(value["variants"], list):
        raise ContractValidationError("invalid_type", path + ".variants", "expected array")
    if len(value["variants"]) < 1:
        raise ContractValidationError("invalid_value", path + ".variants", "fewer than minItems 1")
    if len(value["variants"]) > 250:
        raise ContractValidationError("invalid_value", path + ".variants", "more than maxItems 250")
    for _i1, _v1 in enumerate(value["variants"]):
        if not isinstance(_v1, dict):
            raise ContractValidationError("invalid_type", path + ".variants" + "[" + str(_i1) + "]", "expected object")
        _allowed2 = frozenset(("available", "price", "title", "variant_id",))
        for _k2 in sorted(_v1):
            if _k2 not in _allowed2:
                raise ContractValidationError("unknown_field", path + ".variants" + "[" + str(_i1) + "]" + "." + _k2, "unknown field")
        if "variant_id" not in _v1:
            raise ContractValidationError("missing_required", path + ".variants" + "[" + str(_i1) + "]" + ".variant_id", "missing required field")
        if "price" not in _v1:
            raise ContractValidationError("missing_required", path + ".variants" + "[" + str(_i1) + "]" + ".price", "missing required field")
        if "available" not in _v1:
            raise ContractValidationError("missing_required", path + ".variants" + "[" + str(_i1) + "]" + ".available", "missing required field")
        if not isinstance(_v1["available"], bool):
            raise ContractValidationError("invalid_type", path + ".variants" + "[" + str(_i1) + "]" + ".available", "expected boolean")
        validate_money(_v1["price"], path + ".variants" + "[" + str(_i1) + "]" + ".price")
        if "title" in _v1:
            if not isinstance(_v1["title"], str):
                raise ContractValidationError("invalid_type", path + ".variants" + "[" + str(_i1) + "]" + ".title", "expected string")
            if len(_v1["title"]) < 1:
                raise ContractValidationError("invalid_value", path + ".variants" + "[" + str(_i1) + "]" + ".title", "shorter than minLength 1")
            if len(_v1["title"]) > 300:
                raise ContractValidationError("invalid_value", path + ".variants" + "[" + str(_i1) + "]" + ".title", "longer than maxLength 300")
        validate_ids_variant_id(_v1["variant_id"], path + ".variants" + "[" + str(_i1) + "]" + ".variant_id")
    if "vendor" in value:
        if not isinstance(value["vendor"], str):
            raise ContractValidationError("invalid_type", path + ".vendor", "expected string")
        if len(value["vendor"]) < 1:
            raise ContractValidationError("invalid_value", path + ".vendor", "shorter than minLength 1")
        if len(value["vendor"]) > 120:
            raise ContractValidationError("invalid_value", path + ".vendor", "longer than maxLength 120")


def validate_remove_discount_code_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("expected_revision",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")


def validate_remove_discount_code_output(value, path="$"):
    validate_cart(value, path)


def validate_remove_from_cart_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("expected_revision",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")


def validate_remove_from_cart_output(value, path="$"):
    validate_cart(value, path)


def validate_replace_cart_items_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("expected_revision", "items",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "items" not in value:
        raise ContractValidationError("missing_required", path + ".items", "missing required field")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")
    if not isinstance(value["items"], list):
        raise ContractValidationError("invalid_type", path + ".items", "expected array")
    if len(value["items"]) < 0:
        raise ContractValidationError("invalid_value", path + ".items", "fewer than minItems 0")
    if len(value["items"]) > 200:
        raise ContractValidationError("invalid_value", path + ".items", "more than maxItems 200")
    for _i1, _v1 in enumerate(value["items"]):
        validate_line_item_input(_v1, path + ".items" + "[" + str(_i1) + "]")


def validate_replace_cart_items_output(value, path="$"):
    validate_cart(value, path)


def validate_search_products_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("category", "currency", "cursor", "limit", "price_max_minor", "price_min_minor", "q",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "q" not in value:
        raise ContractValidationError("missing_required", path + ".q", "missing required field")
    if "category" in value:
        if not isinstance(value["category"], str):
            raise ContractValidationError("invalid_type", path + ".category", "expected string")
        if len(value["category"]) < 1:
            raise ContractValidationError("invalid_value", path + ".category", "shorter than minLength 1")
        if len(value["category"]) > 120:
            raise ContractValidationError("invalid_value", path + ".category", "longer than maxLength 120")
    if "currency" in value:
        if not isinstance(value["currency"], str):
            raise ContractValidationError("invalid_type", path + ".currency", "expected string")
        if not _RE_2.fullmatch(value["currency"]):
            raise ContractValidationError("invalid_value", path + ".currency", "does not match pattern ^[A-Z]{3}$")
    if "cursor" in value:
        validate_ids_cursor(value["cursor"], path + ".cursor")
    if "limit" in value:
        if not isinstance(value["limit"], int) or isinstance(value["limit"], bool):
            raise ContractValidationError("invalid_type", path + ".limit", "expected integer")
        if value["limit"] < 1:
            raise ContractValidationError("invalid_value", path + ".limit", "below minimum 1")
        if value["limit"] > 100:
            raise ContractValidationError("invalid_value", path + ".limit", "above maximum 100")
    if "price_max_minor" in value:
        if not isinstance(value["price_max_minor"], int) or isinstance(value["price_max_minor"], bool):
            raise ContractValidationError("invalid_type", path + ".price_max_minor", "expected integer")
        if value["price_max_minor"] < 0:
            raise ContractValidationError("invalid_value", path + ".price_max_minor", "below minimum 0")
    if "price_min_minor" in value:
        if not isinstance(value["price_min_minor"], int) or isinstance(value["price_min_minor"], bool):
            raise ContractValidationError("invalid_type", path + ".price_min_minor", "expected integer")
        if value["price_min_minor"] < 0:
            raise ContractValidationError("invalid_value", path + ".price_min_minor", "below minimum 0")
    if not isinstance(value["q"], str):
        raise ContractValidationError("invalid_type", path + ".q", "expected string")
    if len(value["q"]) < 1:
        raise ContractValidationError("invalid_value", path + ".q", "shorter than minLength 1")
    if len(value["q"]) > 200:
        raise ContractValidationError("invalid_value", path + ".q", "longer than maxLength 200")


def validate_search_products_output(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("page", "results",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "results" not in value:
        raise ContractValidationError("missing_required", path + ".results", "missing required field")
    if "page" not in value:
        raise ContractValidationError("missing_required", path + ".page", "missing required field")
    validate_pagination(value["page"], path + ".page")
    if not isinstance(value["results"], list):
        raise ContractValidationError("invalid_type", path + ".results", "expected array")
    if len(value["results"]) < 0:
        raise ContractValidationError("invalid_value", path + ".results", "fewer than minItems 0")
    if len(value["results"]) > 100:
        raise ContractValidationError("invalid_value", path + ".results", "more than maxItems 100")
    for _i1, _v1 in enumerate(value["results"]):
        validate_product(_v1, path + ".results" + "[" + str(_i1) + "]")


def validate_select_shipping_option_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("expected_revision", "option_id",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "option_id" not in value:
        raise ContractValidationError("missing_required", path + ".option_id", "missing required field")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")
    validate_ids_shipping_option_id(value["option_id"], path + ".option_id")


def validate_select_shipping_option_output(value, path="$"):
    validate_checkout(value, path)


def validate_set_shipping_address_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("address", "expected_revision",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "address" not in value:
        raise ContractValidationError("missing_required", path + ".address", "missing required field")
    validate_address(value["address"], path + ".address")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")


def validate_set_shipping_address_output(value, path="$"):
    validate_checkout(value, path)


def validate_shipping_option(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("carrier", "eta_days_max", "eta_days_min", "label", "option_id", "price",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "option_id" not in value:
        raise ContractValidationError("missing_required", path + ".option_id", "missing required field")
    if "label" not in value:
        raise ContractValidationError("missing_required", path + ".label", "missing required field")
    if "price" not in value:
        raise ContractValidationError("missing_required", path + ".price", "missing required field")
    if "carrier" in value:
        if not isinstance(value["carrier"], str):
            raise ContractValidationError("invalid_type", path + ".carrier", "expected string")
        if len(value["carrier"]) < 1:
            raise ContractValidationError("invalid_value", path + ".carrier", "shorter than minLength 1")
        if len(value["carrier"]) > 64:
            raise ContractValidationError("invalid_value", path + ".carrier", "longer than maxLength 64")
    if "eta_days_max" in value:
        if not isinstance(value["eta_days_max"], int) or isinstance(value["eta_days_max"], bool):
            raise ContractValidationError("invalid_type", path + ".eta_days_max", "expected integer")
        if value["eta_days_max"] < 0:
            raise ContractValidationError("invalid_value", path + ".eta_days_max", "below minimum 0")
        if value["eta_days_max"] > 60:
            raise ContractValidationError("invalid_value", path + ".eta_days_max", "above maximum 60")
    if "eta_days_min" in value:
        if not isinstance(value["eta_days_min"], int) or isinstance(value["eta_days_min"], bool):
            raise ContractValidationError("invalid_type", path + ".eta_days_min", "expected integer")
        if value["eta_days_min"] < 0:
            raise ContractValidationError("invalid_value", path + ".eta_days_min", "below minimum 0")
        if value["eta_days_min"] > 60:
            raise ContractValidationError("invalid_value", path + ".eta_days_min", "above maximum 60")
    if not isinstance(value["label"], str):
        raise ContractValidationError("invalid_type", path + ".label", "expected string")
    if len(value["label"]) < 1:
        raise ContractValidationError("invalid_value", path + ".label", "shorter than minLength 1")
    if len(value["label"]) > 120:
        raise ContractValidationError("invalid_value", path + ".label", "longer than maxLength 120")
    validate_ids_shipping_option_id(value["option_id"], path + ".option_id")
    validate_money(value["price"], path + ".price")


def validate_update_cart_item_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("expected_revision", "quantity",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "quantity" not in value:
        raise ContractValidationError("missing_required", path + ".quantity", "missing required field")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")
    if not isinstance(value["quantity"], int) or isinstance(value["quantity"], bool):
        raise ContractValidationError("invalid_type", path + ".quantity", "expected integer")
    if value["quantity"] < 1:
        raise ContractValidationError("invalid_value", path + ".quantity", "below minimum 1")
    if value["quantity"] > 999:
        raise ContractValidationError("invalid_value", path + ".quantity", "above maximum 999")


def validate_update_cart_item_output(value, path="$"):
    validate_cart(value, path)


def validate_update_checkout_input(value, path="$"):
    if not isinstance(value, dict):
        raise ContractValidationError("invalid_type", path, "expected object")
    _allowed1 = frozenset(("buyer_principal", "expected_revision", "shipping_address",))
    for _k1 in sorted(value):
        if _k1 not in _allowed1:
            raise ContractValidationError("unknown_field", path + "." + _k1, "unknown field")
    if "buyer_principal" in value:
        validate_ids_principal_id(value["buyer_principal"], path + ".buyer_principal")
    if "expected_revision" in value:
        if not isinstance(value["expected_revision"], int) or isinstance(value["expected_revision"], bool):
            raise ContractValidationError("invalid_type", path + ".expected_revision", "expected integer")
        if value["expected_revision"] < 0:
            raise ContractValidationError("invalid_value", path + ".expected_revision", "below minimum 0")
    if "shipping_address" in value:
        validate_address(value["shipping_address"], path + ".shipping_address")


def validate_update_checkout_output(value, path="$"):
    validate_checkout(value, path)


OPERATIONS = {
    "add_to_cart": {
        "contract_version": "1.0.0",
        "method": "POST",
        "path": "/api/auteric/v1/carts/{cart_id}/items",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_add_to_cart_input,
        "output_validator": validate_add_to_cart_output,
    },
    "apply_discount_code": {
        "contract_version": "1.0.0",
        "method": "POST",
        "path": "/api/auteric/v1/carts/{cart_id}/discount-codes",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_apply_discount_code_input,
        "output_validator": validate_apply_discount_code_output,
    },
    "cancel_cart": {
        "contract_version": "1.0.0",
        "method": "POST",
        "path": "/api/auteric/v1/carts/{cart_id}/cancel",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_cancel_cart_input,
        "output_validator": validate_cancel_cart_output,
    },
    "cancel_checkout": {
        "contract_version": "1.0.0",
        "method": "POST",
        "path": "/api/auteric/v1/checkouts/{checkout_id}/cancel",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_cancel_checkout_input,
        "output_validator": validate_cancel_checkout_output,
    },
    "complete_checkout": {
        "contract_version": "1.0.0",
        "method": "POST",
        "path": "/api/auteric/v1/checkouts/{checkout_id}/complete",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_complete_checkout_input,
        "output_validator": validate_complete_checkout_output,
    },
    "create_cart": {
        "contract_version": "1.0.0",
        "method": "POST",
        "path": "/api/auteric/v1/carts",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_create_cart_input,
        "output_validator": validate_create_cart_output,
    },
    "create_checkout": {
        "contract_version": "1.0.0",
        "method": "POST",
        "path": "/api/auteric/v1/checkouts",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_create_checkout_input,
        "output_validator": validate_create_checkout_output,
    },
    "get_cart": {
        "contract_version": "1.0.0",
        "method": "GET",
        "path": "/api/auteric/v1/carts/{cart_id}",
        "side_effect": "read",
        "idempotency": "not_required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_get_cart_input,
        "output_validator": validate_get_cart_output,
    },
    "get_checkout": {
        "contract_version": "1.0.0",
        "method": "GET",
        "path": "/api/auteric/v1/checkouts/{checkout_id}",
        "side_effect": "read",
        "idempotency": "not_required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_get_checkout_input,
        "output_validator": validate_get_checkout_output,
    },
    "get_order": {
        "contract_version": "1.0.0",
        "method": "GET",
        "path": "/api/auteric/v1/orders/{order_id}",
        "side_effect": "read",
        "idempotency": "not_required",
        "identity": "buyer_principal",
        "input_validator": validate_get_order_input,
        "output_validator": validate_get_order_output,
    },
    "get_product": {
        "contract_version": "1.0.0",
        "method": "GET",
        "path": "/api/auteric/v1/products/{product_id}",
        "side_effect": "read",
        "idempotency": "not_required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_get_product_input,
        "output_validator": validate_get_product_output,
    },
    "get_shipping_options": {
        "contract_version": "1.0.0",
        "method": "GET",
        "path": "/api/auteric/v1/carts/{cart_id}/shipping-options",
        "side_effect": "read",
        "idempotency": "not_required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_get_shipping_options_input,
        "output_validator": validate_get_shipping_options_output,
    },
    "remove_discount_code": {
        "contract_version": "1.0.0",
        "method": "DELETE",
        "path": "/api/auteric/v1/carts/{cart_id}/discount-codes/{code}",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_remove_discount_code_input,
        "output_validator": validate_remove_discount_code_output,
    },
    "remove_from_cart": {
        "contract_version": "1.0.0",
        "method": "DELETE",
        "path": "/api/auteric/v1/carts/{cart_id}/items/{line_id}",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_remove_from_cart_input,
        "output_validator": validate_remove_from_cart_output,
    },
    "replace_cart_items": {
        "contract_version": "1.0.0",
        "method": "PUT",
        "path": "/api/auteric/v1/carts/{cart_id}/items",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_replace_cart_items_input,
        "output_validator": validate_replace_cart_items_output,
    },
    "search_products": {
        "contract_version": "1.0.0",
        "method": "GET",
        "path": "/api/auteric/v1/products/search",
        "side_effect": "read",
        "idempotency": "not_required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_search_products_input,
        "output_validator": validate_search_products_output,
    },
    "select_shipping_option": {
        "contract_version": "1.0.0",
        "method": "PUT",
        "path": "/api/auteric/v1/checkouts/{checkout_id}/shipping-option",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_select_shipping_option_input,
        "output_validator": validate_select_shipping_option_output,
    },
    "set_shipping_address": {
        "contract_version": "1.0.0",
        "method": "PUT",
        "path": "/api/auteric/v1/checkouts/{checkout_id}/shipping-address",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_set_shipping_address_input,
        "output_validator": validate_set_shipping_address_output,
    },
    "update_cart_item": {
        "contract_version": "1.0.0",
        "method": "PATCH",
        "path": "/api/auteric/v1/carts/{cart_id}/items/{line_id}",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_update_cart_item_input,
        "output_validator": validate_update_cart_item_output,
    },
    "update_checkout": {
        "contract_version": "1.0.0",
        "method": "PATCH",
        "path": "/api/auteric/v1/checkouts/{checkout_id}",
        "side_effect": "write",
        "idempotency": "required",
        "identity": "buyer_or_guest_principal",
        "input_validator": validate_update_checkout_input,
        "output_validator": validate_update_checkout_output,
    },
}


def validate_input(operation, data):
    """Validate a tool-call input payload for operation; raises ContractValidationError."""
    if operation not in OPERATIONS:
        raise KeyError(f"unknown operation {operation!r}")
    OPERATIONS[operation]["input_validator"](data)


def validate_output(operation, data):
    """Validate a merchant response payload for operation; raises ContractValidationError."""
    if operation not in OPERATIONS:
        raise KeyError(f"unknown operation {operation!r}")
    OPERATIONS[operation]["output_validator"](data)
